version: '2'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: sample
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: CHANGME
    volumes:
      - ./www:/var/www/html

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: CHANGME
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
